eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring: 
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true 
  datasource:
    url:  url: jdbc:mysql://localhost:3306/db
    username: usuario
    password: usuario
