server:
  port: 3032
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9191/eureka/
spring: 
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: usuario
    password: usuario
spc:
  pessoa:
    fisica: 
      url: https://5ce01836fc90670014267d15.mockapi.io/spc/pessoaFisica
    juridica:
      url: https://5ce01836fc90670014267d15.mockapi.io/spc/pessoaJuridica
serasa:
  pessoa:
    fisica: 
      url: https://5ce190698ad3c700145b7cfb.mockapi.io/serasa/pessoaFisica
    juridica:
      url: https://5ce190698ad3c700145b7cfb.mockapi.io/serasa/pessoaJuridica
boavista:
  pessoa:
    fisica: 
      url: https://5ce190868ad3c700145b7d02.mockapi.io/boavista/pessoaFisica
    juridica:
      url: https://5ce190868ad3c700145b7d02.mockapi.io/boavista/pessoaJuridica
