eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
spring: 
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true 
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: usuario
    password: usuario
